import java_cup.runtime.*;
import java.util.*;
import java.io.*;

parser code
{:

    @Override
    public void syntax_error(Symbol s){

        ErrorManager.addError(
                "Sintáctico",
                "Error sintáctico",
                s.left + 1,
                s.right + 1
        );

        System.out.println(
                "❌ Error sintáctico en línea "
                        + (s.left + 1)
                        + ", columna "
                        + (s.right + 1)
        );
    }

:};

// =====================================
// TERMINALES
// =====================================

terminal SET_START, SET_END;
terminal INICIO, FIN;

terminal VENN;

terminal UNION;
terminal INTERSECCION;
terminal DIFERENCIA;
terminal DIF_SIM;

terminal LLAVE_IZQ;
terminal LLAVE_DER;

terminal PAR_IZQ;
terminal PAR_DER;

terminal COMA;
terminal PYC;

terminal IGUAL;

terminal Integer NUMERO;
terminal String ID;

// =====================================
// NO TERMINALES
// =====================================

non terminal programa;
non terminal lista_sentencias;
non terminal statement;

non terminal Set<Integer> conjunto;
non terminal Set<Integer> lista;
non terminal Set<Integer> expr;

// =====================================
// PRECEDENCIA
// =====================================

precedence left UNION;
precedence left INTERSECCION;
precedence left DIFERENCIA;
precedence left DIF_SIM;

// =====================================
// INICIO
// =====================================

start with programa;

// =====================================
// PROGRAMA
// =====================================

programa ::=
    SET_START
    INICIO
    lista_sentencias
    FIN
    SET_END
{:

    ReportGenerator.generarReporte();

:}
;

// =====================================
// LISTA SENTENCIAS
// =====================================

lista_sentencias ::=
      lista_sentencias statement
    | statement
;

// =====================================
// SENTENCIAS
// =====================================

statement ::=

    // =================================
    // DECLARACIÓN CONJUNTOS
    // =================================

    ID:id IGUAL conjunto:c PYC
    {:

        SymbolTable.put(
                id,
                c
        );

        System.out.println(
                "Conjunto guardado: "
                        + id + " = " + c
        );

    :}

    // =================================
    // OPERACIONES
    // =================================

    | ID:id IGUAL expr:e PYC
    {:

        SymbolTable.put(
                id,
                e
        );

        System.out.println(
                "Resultado guardado: "
                        + id + " = " + e
        );

    :}

    // =================================
    // VENN
    // =================================

    | VENN PAR_IZQ expr:e PAR_DER PYC
    {:

        System.out.println(
                "\n========= VENN ========="
        );

        System.out.println(
                "Resultado: " + e
        );

        System.out.println(
                "========================\n"
        );

        Set<Integer> A = null;
        Set<Integer> B = null;

        // =============================
        // UNION
        // =============================

        if(VennGenerator.operacionActual.contains("∪")){

            String[] partes =
                    VennGenerator.operacionActual.split("∪");

            A = SymbolTable.get(
                    partes[0].trim()
            );

            B = SymbolTable.get(
                    partes[1].trim()
            );
        }

        // =============================
        // INTERSECCION
        // =============================

        else if(VennGenerator.operacionActual.contains("∩")){

            String[] partes =
                    VennGenerator.operacionActual.split("∩");

            A = SymbolTable.get(
                    partes[0].trim()
            );

            B = SymbolTable.get(
                    partes[1].trim()
            );
        }

        // =============================
        // DIFERENCIA
        // =============================

        else if(VennGenerator.operacionActual.contains("-")){

            String[] partes =
                    VennGenerator.operacionActual.split("-");

            A = SymbolTable.get(
                    partes[0].trim()
            );

            B = SymbolTable.get(
                    partes[1].trim()
            );
        }

        // =============================
        // DIF SIMETRICA
        // =============================

        else if(VennGenerator.operacionActual.contains("Δ")){

            String[] partes =
                    VennGenerator.operacionActual.split("Δ");

            A = SymbolTable.get(
                    partes[0].trim()
            );

            B = SymbolTable.get(
                    partes[1].trim()
            );
        }

        // =============================
        // GENERAR DIAGRAMA
        // =============================

        if(A != null && B != null){

            VennGenerator.generar(
                    VennGenerator.operacionActual,
                    e,
                    A,
                    B
            );
        }

    :}

    // =================================
    // RECUPERACION ERRORES
    // =================================

    | error PYC
;

// =====================================
// EXPRESIONES
// =====================================

expr ::=

    // =================================
    // UNION
    // =================================

    ID:a UNION ID:b
    {:

        Set<Integer> A =
                SymbolTable.get(a);

        Set<Integer> B =
                SymbolTable.get(b);

        VennGenerator.operacionActual =
                a + " ∪ " + b;

        if(A != null && B != null){

            RESULT =
                    SetOperations.union(A, B);

            System.out.println(
                    "UNIÓN = " + RESULT
            );

        } else {

            RESULT =
                    new HashSet<Integer>();
        }

    :}

    // =================================
    // INTERSECCION
    // =================================

    | ID:a INTERSECCION ID:b
    {:

        Set<Integer> A =
                SymbolTable.get(a);

        Set<Integer> B =
                SymbolTable.get(b);

        VennGenerator.operacionActual =
                a + " ∩ " + b;

        if(A != null && B != null){

            RESULT =
                    SetOperations.interseccion(A, B);

            System.out.println(
                    "INTERSECCIÓN = "
                            + RESULT
            );

        } else {

            RESULT =
                    new HashSet<Integer>();
        }

    :}

    // =================================
    // DIFERENCIA
    // =================================

    | ID:a DIFERENCIA ID:b
    {:

        Set<Integer> A =
                SymbolTable.get(a);

        Set<Integer> B =
                SymbolTable.get(b);

        VennGenerator.operacionActual =
                a + " - " + b;

        if(A != null && B != null){

            RESULT =
                    SetOperations.diferencia(A, B);

            System.out.println(
                    "DIFERENCIA = "
                            + RESULT
            );

        } else {

            RESULT =
                    new HashSet<Integer>();
        }

    :}

    // =================================
    // DIFERENCIA SIMETRICA
    // =================================

    | ID:a DIF_SIM ID:b
    {:

        Set<Integer> A =
                SymbolTable.get(a);

        Set<Integer> B =
                SymbolTable.get(b);

        VennGenerator.operacionActual =
                a + " Δ " + b;

        if(A != null && B != null){

            RESULT =
                    SetOperations.diferenciaSimetrica(A, B);

            System.out.println(
                    "DIFERENCIA SIMÉTRICA = "
                            + RESULT
            );

        } else {

            RESULT =
                    new HashSet<Integer>();
        }

    :}

    // =================================
    // SOLO ID
    // =================================

    | ID:id
    {:

        RESULT =
                SymbolTable.get(id);

    :}
;

// =====================================
// CONJUNTOS
// =====================================

conjunto ::=
    LLAVE_IZQ lista:l LLAVE_DER
    {:

        if(l.isEmpty()){

            ErrorManager.addError(
                    "Semántico",
                    "Conjunto vacío no permitido",
                    0,
                    0
            );
        }

        RESULT = l;

    :}
;

// =====================================
// LISTA ELEMENTOS
// =====================================

lista ::=

    NUMERO:n
    {:

        RESULT =
                new HashSet<Integer>();

        RESULT.add(n);

    :}

    | lista:l COMA NUMERO:n
    {:

        l.add(n);

        RESULT = l;

    :}
;