
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 9;
  public static final int PYC = 16;
  public static final int IGUAL = 17;
  public static final int SET_END = 3;
  public static final int INTERSECCION = 8;
  public static final int ID = 19;
  public static final int COMA = 15;
  public static final int EOF = 0;
  public static final int PAR_IZQ = 13;
  public static final int UNION = 7;
  public static final int NUMERO = 18;
  public static final int error = 1;
  public static final int PAR_DER = 14;
  public static final int LLAVE_IZQ = 11;
  public static final int SET_START = 2;
  public static final int DIF_SIM = 10;
  public static final int LLAVE_DER = 12;
  public static final int VENN = 6;
  public static final int FIN = 5;
  public static final int INICIO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SET_START",
  "SET_END",
  "INICIO",
  "FIN",
  "VENN",
  "UNION",
  "INTERSECCION",
  "DIFERENCIA",
  "DIF_SIM",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "PAR_IZQ",
  "PAR_DER",
  "COMA",
  "PYC",
  "IGUAL",
  "NUMERO",
  "ID"
  };
}

