
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PERTENECE = 16;
  public static final int LLAVE_ABRE = 18;
  public static final int DIFERENCIA = 13;
  public static final int LLAVE_CIERRA = 19;
  public static final int PAREN_ABRE = 20;
  public static final int SET_END = 3;
  public static final int ENTONCES = 7;
  public static final int INTERSECCION = 12;
  public static final int ID = 26;
  public static final int IGUALDAD = 17;
  public static final int CARACTER = 27;
  public static final int DIF_SIMETRICA = 14;
  public static final int COMA = 22;
  public static final int ASIGNACION = 24;
  public static final int PAREN_CIERRA = 21;
  public static final int EOF = 0;
  public static final int UNION = 11;
  public static final int SI = 6;
  public static final int error = 1;
  public static final int PARA_CADA = 8;
  public static final int PUNTO_COMA = 23;
  public static final int EN = 9;
  public static final int SET_START = 2;
  public static final int ENTERO = 25;
  public static final int SUBCONJUNTO = 15;
  public static final int VENN = 10;
  public static final int FIN = 5;
  public static final int INICIO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SET_START",
  "SET_END",
  "INICIO",
  "FIN",
  "SI",
  "ENTONCES",
  "PARA_CADA",
  "EN",
  "VENN",
  "UNION",
  "INTERSECCION",
  "DIFERENCIA",
  "DIF_SIMETRICA",
  "SUBCONJUNTO",
  "PERTENECE",
  "IGUALDAD",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "PAREN_ABRE",
  "PAREN_CIERRA",
  "COMA",
  "PUNTO_COMA",
  "ASIGNACION",
  "ENTERO",
  "ID",
  "CARACTER"
  };
}

